### ISSUE TITLE
install-maven.sh outdated binary

### ISSUE THREAD

**Issue by quangmng** [Birch-san/arm-editor-launcher#2]
Hi there, I suspect your install-maven.sh file returned a 404 link in line 8, 
hence "error opening archive".

<img width="1096" alt="404 link" src="https://user-images.githubusercontent.com/57740309/168423114-6193e1ef-ca74-41e4-8b57-b4c1567a6d00.png">
(maven-3.8.4 404'ed)

<img width="572" alt="returned 404 in line 8" src="https://user-images.githubusercontent.com/57740309/168423024-a6dc4d58-b784-4ccf-8684-f6909f4911a9.png">

**Comment by Birch-san** [comment]
thanks; have now pushed an update to 3.8.5.
