### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Moebytes** [Birch-san/arm-editor-launcher#6]
.

**Comment by Birch-san** [comment]
This happened before:
https://github.com/Birch-san/arm-editor-launcher/issues/2

 it's a moving target; try 3.8.6 or 3.8.7, etc. or search the Maven website to discover what the latest version is meant to be. 😛

**Comment by Tenpi** [comment]
Seems like this will break very often, can't you just get the latest version programmatically? 

Maybe this answer could be of help.
https://stackoverflow.com/a/58687578
