### ISSUE TITLE
Live2D Cubism 4.1.05  Not working on macOS Monterey 12.5

### ISSUE THREAD

**Issue by SuCicada** [Birch-san/arm-editor-launcher#7]
I tried running it last month, it opens perfectly, it's great
But now I run it again and it keeps getting stuck on the splash screen.
In the activity monitor has been not responding state. I've waited for a long time, no progress。

i tried
1. Reinstall live2d cubism 4.1.05
2. Uninstall live2d cubism 4.1.05 . Install 4.2.01 beta1 . And modify the version number in the corresponding pom and code
3. Recompile (gradle clean install)
4. Restart the computer
But still not

Your technology is amazing. Please help me, I don't know much about java17 black magic. thank you very much

<img width="501" alt="image" src="https://user-images.githubusercontent.com/33519267/192127045-c396f0ab-6799-47c8-98fa-7af7bb8ba2e1.png">

![image](https://user-images.githubusercontent.com/33519267/192127058-1839a65a-e746-4f2d-9d7f-68c8c57bd84a.png)

## JDK
azul-17.0.4.1

## Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1
  Serial Number (system):	CW0VYCGW2L
  Hardware UUID:	A1670691-E657-5728-A5F1-B505C65A656E
  Provisioning UDID:	00006000-0000682C1A62801E
  Activation Lock Status:	Enabled

**Comment by Birch-san** [comment]
updated for 4.2.01:  
https://github.com/Birch-san/arm-editor-launcher/commit/b4fd37cb7fccf2090e163fc0ff9368fd63d1344f

thanks for telling me.

pull the latest commit, tell IntelliJ to reload all Maven Projects (this will update classpaths to point to 4.2, which fixes your run configurations):  
<img width="243" alt="image" src="https://user-images.githubusercontent.com/6141784/193363317-6d1e7926-a6c6-4167-9d70-04547ea44e92.png">

maven clean, then maven install, the root-level project from the Maven toolwindow:  
_I didn't wanna take two screenshots so here I did a multiselect but only to highlight them._  
<img width="422" alt="image" src="https://user-images.githubusercontent.com/6141784/193363396-a64702df-1a7e-45d4-a316-7963ff4ab116.png">  

Run the launcher as usual:  
<img width="394" alt="image" src="https://user-images.githubusercontent.com/6141784/193363545-bc8b41ad-119e-4c0a-a714-d284b1eeeade.png">

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/6141784/193363055-eec3bda3-a052-4358-b572-a12e704cc2d9.png">

**Comment by SuCicada** [comment]
Thank you. although I think this past problem is because of https://github.com/Birch-san/arm-editor-launcher/issues/3#issuecomment-1126827040 
but thank you, I love your work
